============================= test session starts ==============================
platform darwin -- Python 3.8.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1 -- /Users/meganfrenkel/Workspace/KERMit/server/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/meganfrenkel/Workspace/KERMit
plugins: mock-3.3.1
collecting ... collected 102 items

server/tests/unit/test_authentication.py::test_authorize_token_missing_header PASSED [  0%]
server/tests/unit/test_authentication.py::test_authorize_token_missing_header2 PASSED [  1%]
server/tests/unit/test_authentication.py::test_authorize_token_malformed_header PASSED [  2%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_error PASSED [  3%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_success_register PASSED [  4%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_success PASSED [  5%]
server/tests/unit/test_authentication.py::test_authorize_token_validation_not_registered PASSED [  6%]
server/tests/unit/test_authentication.py::test_register_already_registered PASSED [  7%]
server/tests/unit/test_authentication.py::test_register_missing_info_email PASSED [  8%]
server/tests/unit/test_authentication.py::test_register_missing_info_id PASSED [  9%]
server/tests/unit/test_authentication.py::test_register_error_googleauth PASSED [ 10%]
server/tests/unit/test_authentication.py::test_register_exception PASSED [ 11%]
server/tests/unit/test_authentication.py::test_register_user_not_registered PASSED [ 12%]
server/tests/unit/test_authentication.py::test_register_exception_db PASSED [ 13%]
server/tests/unit/test_google_auth.py::test_validate_token PASSED        [ 14%]
server/tests/unit/test_google_auth.py::test_get_user_information PASSED  [ 15%]
server/tests/unit/test_leaderboard.py::test_get_leaderboard_no_leaders PASSED [ 16%]
server/tests/unit/test_leaderboard.py::test_get_leaderboard PASSED       [ 17%]
server/tests/unit/test_player.py::test_save_commit PASSED                [ 18%]
server/tests/unit/test_player.py::test_save PASSED                       [ 19%]
server/tests/unit/test_player.py::test_find_all_puzzles_for_player PASSED [ 20%]
server/tests/unit/test_player.py::test_find_players_for_puzzle PASSED    [ 21%]
server/tests/unit/test_player.py::test_add_player_to_puzzle_already_too_many_players PASSED [ 22%]
server/tests/unit/test_player.py::test_add_player_to_puzzle_player_doesnt_exist PASSED [ 23%]
server/tests/unit/test_player.py::test_add_player_to_puzzle_ok PASSED    [ 24%]
server/tests/unit/test_player.py::test_to_player_to_str PASSED           [ 25%]
server/tests/unit/test_puzzle_exception.py::test_get_message PASSED      [ 26%]
server/tests/unit/test_puzzle_pieces.py::test_find_all_pieces PASSED     [ 27%]
server/tests/unit/test_puzzle_pieces.py::test_get_piece PASSED           [ 28%]
server/tests/unit/test_puzzle_pieces.py::test_get_piece_none PASSED      [ 29%]
server/tests/unit/test_puzzle_pieces.py::test_save_autocommit PASSED     [ 30%]
server/tests/unit/test_puzzle_pieces.py::test_save PASSED                [ 31%]
server/tests/unit/test_puzzle_pieces.py::test_update_success PASSED      [ 32%]
server/tests/unit/test_puzzle_pieces.py::test_update_fail_static PASSED  [ 33%]
server/tests/unit/test_puzzle_pieces.py::test_get_as_str PASSED          [ 34%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_valid_defaults PASSED [ 35%]
server/tests/unit/test_sudoku_puzzle.py::test_create_puzzle_valid_specification PASSED [ 36%]
server/tests/unit/test_sudoku_puzzle.py::test_create_puzzle_valid_difficulty_upper_bound PASSED [ 37%]
server/tests/unit/test_sudoku_puzzle.py::test_create_puzzle_valid_difficulty_lower_bound PASSED [ 38%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_difficulty_str PASSED [ 39%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_difficulty_too_low PASSED [ 40%]
server/tests/unit/test_sudoku_puzzle.py::test_create_sudoku_puzzle_invalid_difficulty_too_high PASSED [ 41%]
server/tests/unit/test_sudoku_puzzle.py::test_create_puzzle_valid_size_lower_bound PASSED [ 42%]
server/tests/unit/test_sudoku_puzzle.py::test_create_puzzle_valid_size_upper_bound 